"""изменено поле в beststep

Revision ID: 7b17add827bf
Revises: 951162b009c0
Create Date: 2024-08-30 17:35:52.369630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b17add827bf'
down_revision: Union[str, None] = '951162b009c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('old_games')
    op.add_column('best_step', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_column('best_step', 'seat_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('best_step', sa.Column('seat_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('best_step', 'user_id')
    op.create_table('old_games',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('types_game', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('date_game', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('gamers', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('fols', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False),
    sa.Column('points', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=False),
    sa.Column('dop_points', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.Column('best_step', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('first_dead', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('winner', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='old_games_pkey')
    )
    # ### end Alembic commands ###
