"""Преобразование баз данных3

Revision ID: 89f76b3a1030
Revises: c01849e5e655
Create Date: 2024-08-23 11:57:45.306506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f76b3a1030'
down_revision: Union[str, None] = 'c01849e5e655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_results', sa.Column('player_id', sa.Integer(), nullable=False))
    op.drop_constraint('game_results_playr_id_fkey', 'game_results', type_='foreignkey')
    op.create_foreign_key(None, 'game_results', 'users', ['player_id'], ['id'])
    op.drop_column('game_results', 'playr_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_results', sa.Column('playr_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'game_results', type_='foreignkey')
    op.create_foreign_key('game_results_playr_id_fkey', 'game_results', 'users', ['playr_id'], ['id'])
    op.drop_column('game_results', 'player_id')
    # ### end Alembic commands ###
