"""Преобразование баз данных2

Revision ID: c01849e5e655
Revises: 09b152fdff1d
Create Date: 2024-08-23 11:39:53.156332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c01849e5e655'
down_revision: Union[str, None] = '09b152fdff1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE new_games CASCADE')
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_games', sa.String(length=15), nullable=False),
    sa.Column('date_game', sa.Date(), nullable=False),
    sa.Column('first_dead', sa.String(length=150), nullable=True),
    sa.Column('winner', sa.String(length=15), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('new_games')
    # op.drop_constraint('best_step_game_id_fkey', 'best_step', type_='foreignkey')
    op.create_foreign_key(None, 'best_step', 'games', ['game_id'], ['id'])
    # op.drop_constraint('game_results_game_id_fkey', 'game_results', type_='foreignkey')
    op.create_foreign_key(None, 'game_results', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_results', type_='foreignkey')
    op.create_foreign_key('game_results_game_id_fkey', 'game_results', 'new_games', ['game_id'], ['id'])
    op.drop_constraint(None, 'best_step', type_='foreignkey')
    op.create_foreign_key('best_step_game_id_fkey', 'best_step', 'new_games', ['game_id'], ['id'])
    op.create_table('new_games',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type_games', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('date_game', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('first_dead', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('winner', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='new_games_pkey')
    )
    op.drop_table('games')
    # ### end Alembic commands ###
