"""описание изменений

Revision ID: e03c798ca046
Revises: 
Create Date: 2024-08-05 18:08:21.391171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e03c798ca046'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'first_dead',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('games', 'winner',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'winner',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('games', 'first_dead',
               existing_type=sa.String(length=150),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
